### ISSUE TITLE
Delete bucket scenarios should be put at the last position

### ISSUE THREAD

**Issue by markduan** [qingstor/qingstor-sdk-test-scenarios#21]
https://github.com/yunify/qingstor-sdk-test-scenarios/blob/4a2de34ec41e227dd7172f52cb75842cfa177b5d/bucket.feature#L56

Otherwise, how to execute the following `List Multipart Uploads` scenario?

**Comment by Xuanwo** [comment]
We will remove the create & delete bucket tests.
